# arithamatic operator

In [1]:
# arithamatic operator
a=5
b=5
c=a+b
print(c)

10


In [2]:
a=5
b=5
c=a-b
print(c)

0


In [3]:
a=5
b=5
c=a/b
print(c)

1.0


In [4]:
a=5
b=5
c=a//b
print(c)

1


In [5]:
a=5
b=5
c=a%b
print(c)

0


# assignment operator

In [3]:
# assignment operator
a=5
b=5
a==b

True

In [5]:
a=5
b=5
a!=b

False

# comparision operator

In [2]:
# comparision operator
a=5
b=5
c=a<=b
print(c)

True


In [9]:
a=5
b=5
c=a>=b
print(c)

True


In [10]:
a=5
b=5
c=a<b
print(c)

False


In [11]:
a=5
b=5
c=a>b
print(c)

False


In [3]:
# identifier operator (is, is not)
# -5 to 256 values r called cach which r pre allocated
a=-5
b=-5
a is b

True

In [14]:
# membership operator(in, not in)
a="167555"
"7" in a

True

In [15]:
a="happy hallo"
"h" not in a

False

In [16]:
# bitwise operator or = |
a=5
b=8
a|b

13

In [21]:
# bitwise operator and = &&
a=7
b=9
a&b

1

In [24]:
# bitwise operator not = ~ (rule is n=-(n+1))
a=4
b=6
~b

-7

In [2]:
a=7
b=5
a>>b

0

In [1]:
a=7
b=5
a<<b

224

In [3]:
a=7
b=5
a^b

2

In [1]:
# according to alphabets or strings all charecters r stored in a single space unless theres a space created
a="abcdefghijklmnopqrstuvwxyzhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
b="abcdefghijklmnopqrstuvwxyzhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
a is b

True

In [8]:
a="abcdefghijklmnopqrstuvwxyzhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh jjjjj"
b="abcdefghijklmnopqrstuvwxyzhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh jjjjj"
a is b

False

In [1]:
# infosys= 1yr exp|python|chennai
# wipro =fresh|python|coyambathoor
# tcs =java|fresh|chennai
# cognizant =java|1yr exp|bangalour
a=input("enter your total experiance at work : ")
b=input("enter ur code language : ")
c=input("enter ur prefered location : ")
if (a=="1 year exp" and b == "python" and c=="chennai"):
    print("get ur job in infosys")
elif(a=="fresh year" and b=="python" and c=="coyam"):
    print("get ur job in wipro")
elif(a=="fresh year" and b == "java" and c=="chennai"):
    print("get ur job in tcs")
elif(a=="1 year exp" and b == "java" and c=="bang"):
    print("get ur job in cognizant")
else:
    print("get ur job in others")

enter your total experiance at work :  1 year exp
enter ur code language :  python
enter ur prefered location :  chennai


get ur job in infosys


# create calculator using if condition

In [ ]:
# create calculator using if condition
print("welcome to my calculator")
c=input("enter the method of operation : ")
l_c=c.lower()
if (l_c == "addition"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    print(a+b)
elif (l_c == "subraction"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    print(a-b)
elif (l_c == "multiplication"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    print(a*b)
elif (l_c == "division"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    if(a==0 and b==0):
        print("undefined")
    else:
        print(a/b)
elif (l_c == "floor division"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    if(a==0 and b==0):
        print("undefined")
    else:
        print(a//b)
elif (l_c == "modulas"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    if(a==0 and b==0):
        print("undefined")
    else:
        print(a%b)
elif (c == "exponent"):
    a=int(input("enter the number : "))
    b=int(input("enter the number : "))
    print(a**b)
else:
    print("use only these command 'addition','subraction','multiplication','division','floor division','modulas','exponent' if u don't know spilling u can copy paste too")

welcome to my calculator


In [16]:
a=0
b=8
print(a/b)

0.0


# list,tuple,sets and dict

In [8]:
# list of 10 values, in 2nd index add a new value, remove last value, add a value in last,remove a vaalues
a = [1, 2, 3, 4, "apple", "banana", "minions", "gru", "spider", "run"]
a[2] = "orange"
a.pop(-1) # or a.remove("run")
a.append("man")
print(a)

[1, 2, 'orange', 4, 'apple', 'banana', 'minions', 'gru', 'spider', 'man']


In [22]:
a=[1,2,3,4,5]
a[1:3]=["hi"]
print(a)

[1, 'hi', 4, 5]


In [2]:
a=(1,2,3,4)
b=list(a)
b.pop(1)
a=tuple(b)
print(a)

(1, 3, 4)


In [16]:
a={"hi":7,"hello":8}
a["hello"]=10
print(a)

{'hi': 7, 'hello': 10}


In [3]:
a=5
b=0
a+b

5

In [45]:
# list methods
a=[0,1,2,3,4,5,6,7,8,9,11,12,13,14,10]
b=[15,16,17,"die"]
#a.append("world") # add a value to last
#a.extend(b) # to add another list
#a.insert(0,"see next") # insert a value by index no and value to be inserted
#a.remove(14) #remove name or value
#a.pop(-1) # index number
#a.clear() # clear only the values
#del(a) # to delete whole structure or the variable
#a.index("hello") # to find the value's index
#a.count("hello") #to find the values count
#a.sort() #to sort the list
#a.reverse() #to reverse the list
print(a)
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 10]
[15, 16, 17, 'die']


In [49]:
# tuple
a=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,"ayoo","get","lost"]
#a.index("ayoo") # to find the value's index
a.count(14) #to find the values count
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 'ayoo', 'get', 'lost']


In [73]:
a={10,14,16,"hay","count","go",9,9}
b={9,8,7,"there","number","hell",14,14}
#a.add("to") # add only one value
#a.remove(10) #remove any element by value not index
#a.pop() #remove random values
#a.clear() #clear only the values
#a.discard(10) #remove name or value without error
#a.remove(10) #remove name or value with error
#a.union(b) #join two variable sets with no duplicate
#a.intersection(b) #print only common values without duplicate
#a.difference(b) #print differnt values from b or other variable
#a.issubset(b) #check a values in b
a.issuperset(b) # check b values r in a
#print(a)

False

In [98]:
a={"a":"apple","b":0,40:"doll","aer":900}
#a.pop() # pop a value
#del(a) # to delete whole structure or the variable
#a["a"] # to get keys value
a.items() #to get values a.values()  keys a.keys() all a.items()
a.popitem() # remove last value in dict
#print(a)

('aer', 900)

In [9]:
# nested list
#index position
###0,1,2,3,4,####################   5 , 6###
############0,1,2,3,#########  4 ##^^##^^#
###################### 0 ,1,2##^^^##^^##^^#
a=[1,2,3,4,[7,"hi",7,[12,67,90],9],"ki",0]
a[4][3][1]=88
print(a)

[1, 2, 3, 4, [7, 'hi', 7, [12, 88, 90], 9], 'ki', 0]


In [2]:
# create a table by using dictionary and make them updatable like add,delete,show
a=input("enter the column name : ")
b={
"employee":["aa","bb","cc"],
"id":[1,2,3],
"salary":[500,600,700]
}
if a=="employee":
    op =input("enter the operation name : ")
    if op =="add":
        value=input("enter the value to be added :")
        b["employee"].append(value)
    elif op == "del":
        value=input("enter the value to be deleted :")
        b["employee"].remove(value)
    else:
        print("u can only do add and delete operations to add use 'add' key word to delete use 'del' keyword")
    print(b["employee"])
elif a=="id":
    op =input("enter the operation name : ")
    if op =="add":
        value=input("enter the value to be added :")
        b["id"].append(value)
    elif op == "del":
        value=input("enter the value to be deleted :")
        b["id"].remove(value)
    else:
        print("u can only do add and delete operations to add use 'add' key word to delete use 'del' keyword")
    print(b["id"])
elif a=="salary":
    op =input("enter the operation name : ")
    if op =="add":
        value=input("enter the value to be added :")
        b["salary"].append(value)
    elif op == "del":
        value=input("enter the value to be deleted :")
        b["salary"].remove(value)
    else:
        print("u can only do add and delete operations. To add use 'add' key word to delete use 'del' keyword")
    print(b["salary"])
else:
    print("invalid operation")

enter the column name :  80


invalid operation


# python test

In [2]:
# SECTION A – Basic Programs
# A1. Write a program to check whether a number is Even or Odd.
a=int(input("enter the number : "))
if a%2==0:
    print("even")
else:
    print("odd")

enter the number :  70


even


In [10]:
# A2. Write a program to print grade (A/B/C/D/F) based on marks.
a=int(input("enter the mark : "))
if a>90:
    print("grade A")
elif a>80:
    print("grade B")
elif a>70:
    print("grade C")
elif a>60:
    print("grade D")
else:
    print("grade F")

enter the mark :  91


grade A


In [22]:
# A3. Write a program to check whether a number is Positive, Negative, or Zero.
a=int(input("enter the number : "))
if a<0:
    print("negative")
elif a==0:
    print("zero")
else:
    print("positive")

enter the number :  -9


negative


In [7]:
# A4. Write a program to check whether a year is a Leap Year.
a=int(input("enter the year : "))
if a%4==0:
    print("leap year")
else:
    print("not leap year")

enter the year :  1991


not leap year


In [25]:
# A5. Write a program to find the Smallest of Three Numbers.
a=int(input("enter the number : "))
b=int(input("enter the number : "))
c=int(input("enter the number : "))
if(a<b and a<c):
    print("the smallest number is : ", a)
elif(b<a and b<c):
    print("the smallest number is : ", b)
else:
    print("the smallest number is : ", c)
    

enter the number :  78
enter the number :  89
enter the number :  90


the smallest number is :  78


In [31]:
# A6. Create a Password Validator (Password: Python123).
a=input("enter your password : ")
b="Python123"
if a==b:
    print("wellcome")
else:
    print("try again (O.O)")

enter your password :  op


try again (O.O)


In [36]:
# A7. Create a Simple Calculator using +, -, *, /.
a=input("enter your password : ")
b=int(input("enter the number : "))
c=int(input("enter the number : "))
if a=="+":
    print(b+c)
elif a=="-":
    print(b-c)
elif a=="*":
    print(b*c)
elif a=="/":
    print(b/c)
else:
    print("invalid operator")

enter your password :  /
enter the number :  98
enter the number :  99


0.98989898989899


In [39]:
# A8. Write a program to check Voting Eligibility (age ≥ 18).
a=int(input("enter your age : "))
if(a >= 18):
    print("eligible")
else:
    print("you are a kid")

enter your age :  9


you are a kid


In [14]:
# A9. Write a program to check Character Type (Vowel/Consonant/Other).
a=input("enter char").lower()
b=["a","e","i","o","u"]
c=["b","c","d","f","g","h","j","k","l","m","n","p","q","r","s","t","v","w","x","y","z"]
if a in b:
    print("vowels")
elif a in c:
    print("consonent")
else:
    print("others")

enter char 3


others


In [40]:
# A10. Write a program to check Weekend or Weekday.
a=["saturday","sunday"]
b=input("enter")
if b in a:
    print("weekend")
else:
    print("not weekend")

enter s


not weekend


In [47]:
# SECTION B – List Operations
l = [1, 22, 3, 44, 55, 6, 11, 1200]
m = [1, 2, 3, 546]
l[6]=4      #B1. Insert 4 at 6th index.
l.remove(44)  #B2. Remove value 44.
l.append(88)   #B3. Append 88.
l.pop(2)   #B4. Remove element at 2nd index.
l.extend(m)   #B5. Merge m = [1, 2, 3, 546] with l.
print(l)

[1, 22, 55, 6, 4, 1200, 88, 1, 2, 3, 546]


In [3]:
# SECTION C – String Operations
s = "HelloWorld"
t = "Programming"
a=list(s)
a.insert(6,"python")          #C1. Insert "Python" at 6th index.
a.remove("W")         # C2. Remove "World".
a.append(2024)     #C3. Append "2024".
a.pop(2)     #C4. Remove character at 2nd index.
a.extend(list(t))    #C5. Concatenate t = "Programming".
s=tuple(a)
print(s)

('H', 'e', 'l', 'o', 'python', 'o', 'r', 'l', 'd', 2024, 'P', 'r', 'o', 'g', 'r', 'a', 'm', 'm', 'i', 'n', 'g')


In [59]:
# D3. Simple Login System (Username: admin, Password: 1234).
a=input("enter the username")
b=int(input("enter the pass"))
c="admin"
d=1234
if a==c and b==d:
    print("enter")
else:
    print("get lost")

enter the username kkk
enter the pass 090


get lost


# loops

In [19]:
a=[1,2,3,4,4,3,2,1,5,6] # -> in
b=[]
for i in a:
    if i not in b:
        b.append(i)
print(b)

#a=list(set(a)) -> to remove duplicate
#[1,2,3,4,5,6] -> out

[1, 2, 3, 4, 5, 6]


In [ ]:
a=[1,2,3,4,4,3,2,1,5,6]
b={}
for i in a:
    if i in b:
        b[i]+=1
    else:
        b[i]=1
print(b)
#{1:2,2:2,3:2,4:2,5:1,6:1} ->out

In [1]:
i=0
while i<=6:
    print(i)
    i+=1

0
1
2
3
4
5
6


In [ ]:
i=0
while i<=6:
    print(i)
    i+=1

In [1]:
# max and min of a list
# 2nd smallest and 2nd largest
# 1st method
a=[7,9,8,4,2,0,1]
print("the maximum value is : ",max(a))
print("the minimum value is : ",min(a))
b=sorted(a)
c=b[1]
d=b[-2]
print("the 2nd minimum value is : ",c)
print("the 2nd maximum value is : ",d)

the maximum value is :  9
the minimum value is :  0
the 2nd minimum value is :  1
the 2nd maximum value is :  8


In [2]:
# 2nd method
a=[7,9,8,4,2,0,1]
a.remove(min(a))
a.remove(max(a))
print("the second max is :",max(a))
print("the second min is :",min(a))

the second max is : 8
the second min is : 1


In [10]:
a=[7,9,81,4,2,0,1]
b=a[0]
for i in a:
    if i>b:
        b=i
print(b)

81


In [ ]:

c = input("Enter the operation (+, -, *, /): ")
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
if c == "+":
    print("Sum =", a + b)
elif c == "-":
    print("Difference =", a - b)
elif c == "*":
    print("Multiplication =", a * b)
elif c == "/":
    if b != 0:
        print("Division =", a / b)
    else:
        print("Cannot divide by zero")
else:
    print("Use only '+', '-', '*', '/'")

Enter the operation (+, -, *, /):  +


# question set first 15

In [43]:
# palindrom 101
a=input("enter the word : ").lower().replace(" ","")
b=""
c=""
for i in a:
    if i.isalpha():
        c=c+i
for i in c:
    b=i+b
if b==c:
    print("palindrome")
else:
    print("not palindrome")

enter the word :  m,''o  m


mom
palindrome


In [5]:
a=101
b=str(a)[::-1]
if str(a) == b:
    print("palindrome")
else:
    print("not palindrome")

palindrome


In [7]:
# anagram or not
a=input("enter the string : ")
b=input("enter the string : ")
if sorted(a) == sorted(b):
    print("it is an anagram", a,b)
else:
    print("its not an anagram")

enter the string :  jkl
enter the string :  kkl


its not an anagram


In [6]:
#prime or not
a=int(input("enter the number : "))
if a<=1:
    print("not prime")
else:
    for i in range(2,int(a**0.5)+1):
        if a%i == 0:
            print("not prime")
            break
    else:
        print("prime")

enter the number :  80


not prime


In [1]:
# fibonochi serues
a=int(input("enter total no "))
b=0
c=1
for i in range(a):
    print(b)
    d=b+c
    b=c
    c=d

enter total no  5


0
1
1
2
3


In [5]:
#sort in asc and desc
a=[1,2,5,3,7,5]
a.sort()
b=a[::-1]
print(a)
print(b)

[1, 2, 3, 5, 5, 7]
[7, 5, 5, 3, 2, 1]


In [12]:
# Sum of Digits in a Number
a=input("enter the number : ")
b=0
for i in a:
    b=b+int(i)
print(b)

enter the number :  1234


10


In [18]:
#factorial
a=int(input("enter the number : "))
b=1
for i in range(1,a+1):
    b*=i
print(b)

enter the number :  3


6


In [2]:
# function
a=int(input("in"))
b=int(input("in"))
def add():
    print(a+b)
add()

in 2
in 3


5


# function argument

In [3]:
# function argument
def add(a,b):
    print(a+b)
add(4,1) 

5


In [9]:
def add(a,b):
    c=a+b
    return c
add(a=int(input("in")),
b=int(input("in")))

in 5
in 7


12

# calculator using function and argument

In [19]:
# calculator using function and argument
ope=input("enter the input : ")
def add():
    print(a+b)
def sub():
    print(a-b)
def mul():
    print(a*b)
def div():
    print(a/b)
def fdiv():
    print(a//b)
def mod():
    print(a%b)
def exp():
    print(a**b)
if ope in("add","+","sub", "-","mul","*","div" ,"/","fdiv","//","mod","%","exp" , "**"):
    a=int(input("enter the value : "))
    b=int(input("enter the value : "))
    if ope in ("add", "+"):
        add()
    elif ope in ("sub", "-"):
        sub()
    elif ope in ("mul", "*"):
        mul()
    elif ope in ("div", "/"):
        try:
            div()
        except Exception as e:
            print(e)
    elif ope in ("fdiv", "//"):
        try:
            fdiv()
        except Exception as e:
            print(e)
    elif ope in ("mod", "%"):
        mod()
    elif ope in ("exp", "**"):
        exp()
    else:
        print("invalid input")
else:
    print("u can use only these options. add or +,sub or -,mul or *,div or /,fdiv or //,mod or %,exp or **")

enter the input :  /
enter the value :  0
enter the value :  12


0.0


# while loop

In [ ]:
# print 10 to 200 in sequence
a=10
while a<=200:
    print(a, end=", ")
    a+=10

In [ ]:
# while in reverse
a=10
while a>=0:
    print(a,end=" ")
    a-=1

In [ ]:
# factorial using loop
a=5
b=1
while a>0:
    b=b*a
    a-=1

In [ ]:
a=int(input("e"))
b=1
for i in range(a):
    

# oops (object oriented programming structure or system) class and object

In [2]:
# oops (object oriented programming structure or system) class and object
class calculator():
    def add(self,a,b):
        return a+b
c=calculator()
c.add(5,6)

11

In [17]:
class bank_details:
    cust_name=""
    bank_balance=0.0
    account_no=0
bank=bank_details() # object creation
bank.cust_name="aaa"
bank.bank_balance=14000.80
bank.account_no=9876543210
print(f"""{bank.cust_name}
{bank.bank_balance}
{bank.account_no}""")

aaa
14000.8
9876543210


In [18]:
# constructor
class univ():
    def __init__(self,name,id,email,dele):
        print("yo what's up")
        self.name=name
        self.id=id
        self.email=email
        self.dele=dele
    def __del__(self):
        print("the value is removed",self)
    def __str__(self):
        return(self.dele)
con=univ("aaa","001","queen","data")
con1=univ("bbb",900,"king","bata")
print(con.name,con.id)
print(con1.name,con1.id,con1.email)

yo what's up
the value is removed data
yo what's up
the value is removed bata
aaa 001
bbb 900 king


In [24]:
class bank_details():
    def __init__(self,cust_name,bank_balance,account_no):
        print("your name is : ",cust_name)
        self.cust_name=cust_name
        self.bank_balance=bank_balance
        self.account_no=account_no
bank=bank_details("aaa",14000,9876543210)# object creation
print(bank.cust_name,bank.bank_balance,bank.account_no)

your name is :  aaa
aaa 14000 9876543210


# inheritance (single, multiple,multilevel,hierarchical,hybrid)

In [10]:
# univ , clg , dept in inheritance
#single inheritance
class univ():
    def staff(self,a):
        if a=="present":
            print("welcome to colleget")
        else:
            print("absent")
class college(univ):
    def clg(self):
        print("the colege name is name")
lkg=college()
lkg.staff("present")
lkg.clg()

welcome to colleget
the colege name is name


In [13]:
# multiple inheritance
class univ():
    def __init__(self,staff,student,ntstaff):
        self.staff=staff
        self.student=student
        self.ntstaff=ntstaff
    def uni(self):
        print(self.staff)
class college():
    def clg(self):
        print(self.student)
class department(univ,college):
    def folks(self):
        print(self.ntstaff)
pt=department("ai&ds",50,"nill")
pt.uni()
pt.clg()
pt.folks()

ai&ds
50
nill


In [15]:
#multilevel inheritance
class univ():
    def __init__(self,staff,student,ntstaff):
        self.staff=staff
        self.student=student
        self.ntstaff=ntstaff
    def uni(self):
        print(self.staff)
class college(univ):
    def clg(self):
        print(self.student)
class department(college):
    def folks(self):
        print(self.ntstaff)
pt=department("ai&ds",50,"nill")
pt.uni()
pt.clg()
pt.folks()

ai&ds
50
nill


In [20]:
# Hierarchical Inheritance
class univ():
    def __init__(self,staff,student,ntstaff):
        self.staff=staff
        self.student=student
        self.ntstaff=ntstaff
    def uni(self):
        print(self.staff)
class college(univ):
    def clg(self):
        print(self.student)
class department(univ):
    def folks(self):
        print(self.ntstaff)
pt=department("ai&ds",50,"nill")
pt1=college("cse",60,"mill")
pt.uni()
pt1.clg()
pt.folks()

ai&ds
60
nill


In [22]:
# hybrid inheritance
class univ():
    def __init__(self,staff,student,ntstaff):
        self.staff=staff
        self.student=student
        self.ntstaff=ntstaff
    def uni(self):
        print(self.staff)
class college():
    def clg(self):
        print(self.student)
class department(univ,college):
    def folks(self):
        print(self.ntstaff)
pt=department("ai&ds",50,"nill")
pt.uni()
pt.clg()
pt.folks()

ai&ds
50
nill


# encapsulation

In [15]:
class cap():
    def __init__(self,a,b,c):
        self.a=a
        self._b=b    #-->protected
        self.__c=c   #-->private
    def add(self):
        print(self.a+self._b+self.__c)
d=cap(5,5,10)
d.add()
print(d._b)
#print(d.__c)  #-->cannot take outside the class

20
5


# abstraction

In [6]:
from abc import ABC,abstractmethod
class hide():
    @abstractmethod
    def __init__(self,a,b):
        self.a=a
        self.b=b
    @abstractmethod
    def add(self):
        pass
    @abstractmethod
    def sub(self):
        pass
class calc(hide):
    def add(self):
        print(self.a+self.b)
    def sub(self):
        print(self.a-self.b)
g=calc(5,5)
g.add()
g.sub()

10
0


# staticmethod

In [8]:
from abc import ABC,abstractmethod
class call():
    @staticmethod
    def add(a,b):
        print(a+b)
call.add(5,5) # dont want to create an object

10


# file handling

In [1]:
#r -->read (only read)
#r -->readline (only to read first line)
#r -->readlines (only read but print all lines in one single statement as list only readlines gives list others as string)
#w -->write (delete full text and write the text,also create a fil if no file on the location)
#a -->write (add text to the file ,also create a fil if no file on the location)
#r+ -->read and write (first opens the file and write)
#w+ -->write and read (delete all content from file and create a new content then read)
#with open used as a function
#a=open("a.txt","r") 
#print(a.readline())
#print(a.read())
#print(a.read(7))
#b=open("b.txt","w")
#b.write("damn u idiot don't u know what to do")
#c=open("c.txt","a")
#c.write("get the hell out of here")
#c.close() or a.flush() --> push everything from buffer to file
#with open("a.txt","r") as a: #--> a is a variable and dont need to write close function
#    print(a.read())

# numpy 2d-3d ,3d-2d 3d-1d

In [3]:
#1d to 3d
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(3,2,2)
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
# 3d-2d
import numpy as np 
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
b=a.reshape(4,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#print(len([a]))
#print(a.shape) # -->dimension as (4,3)
#print(a.ndim) # -->dimension number 2
print(a.size) # -->length or total values 12

12


In [13]:
# 2d-3d
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.reshape(3,2,2)
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [19]:
#3d-1d
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
b=a.reshape(12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
pip install pandas

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 11.4 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.9 MB 6.9 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 13.1 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
print(pd.__version__)

3.0.1
